name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Install frontend packages and build frontend
        run: cd react && npm install && npm run build
      - name: Copy project files
        run: gcloud compute scp --recurse react/build/static root@proton-sign-deployed:/var/www/html/ --zone "us-west2-a" && gcloud compute scp react/build/index.html root@proton-sign-deployed:/var/www/html/ --zone "us-west2-a" && gcloud compute scp --recurse php root@proton-sign-deployed:/var/www/html/psignapi --zone "us-west2-a"
